### ISSUE TITLE
app don't work

### ISSUE THREAD

**Issue by hongjr03** [AlexStrNik/LyricsOver#1]
<img width="410" alt="image" src="https://github.com/user-attachments/assets/01200e84-4521-4c6a-bc86-5c761f418916" />

I've tried opening every lyrics panel in apple music however the overlay is empty everytime 😢

**Comment by hongjr03** [comment]
btw the app is running on M3, macOS 15.2

**Comment by AlexStrNik** [comment]
@hongjr03 Hello! Do you start Apple Music before starting LyricsOver? Also, is the LyricsOver app requesting accessibility permissions every time you open it?

**Comment by hongjr03** [comment]
> @hongjr03 Hello! Do you start Apple Music before starting LyricsOver? Also, is the LyricsOver app requesting accessibility permissions every time you open it?

yes, both did but i don't know why the overlay appears empty😭

**Comment by AlexStrNik** [comment]
<img width="771" alt="Screenshot 2024-12-30 at 10 41 21" src="https://github.com/user-attachments/assets/987c3cc2-e01b-405c-b253-c8926a4af89c" />

Could you please send me a screenshot of this panel?

**Comment by hongjr03** [comment]
<img width="827" alt="image" src="https://github.com/user-attachments/assets/798437cc-745c-46dd-8256-230ddc400da2" />

sorry it's a chinese screenshot but it's the same setting panel

**Comment by AlexStrNik** [comment]
@hongjr03 Could you please test the v1.0.1 version that I have just released?

**Comment by hongjr03** [comment]
okay let me try and thanks for your nice work!

**Comment by hongjr03** [comment]
<img width="331" alt="image" src="https://github.com/user-attachments/assets/e87ad1ea-a8a2-4ccc-83a2-0053eb74d0d7" />
it works fine now!
